name: Deploy Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create --name myResourceGroup --location eastus

    - name: Create Static Web App
      run: |
        az staticwebapp create \
          --name my-static-web-app \
          --resource-group myResourceGroup \
          --source https://github.com/${{ github.repository }} \
          --location eastus \
          --branch main \
          --app-location "/" \
          --output-location "build"

    - name: Get Static Web App Deployment Token
      run: |
        DEPLOYMENT_TOKEN=$(az staticwebapp secrets list \
          --name my-static-web-app \
          --resource-group myResourceGroup \
          --query "properties.apiKey" -o tsv)
        echo "DEPLOYMENT_TOKEN=$DEPLOYMENT_TOKEN" >> $GITHUB_ENV

    - name: Build and Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.DEPLOYMENT_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        output_location: "build"
